name: GitHub Action LatexMk
on: [push]
permissions:
  contents: write
jobs:
  paper:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest
    env:
      # Edit here with the names of your latex file and directory (can use ".")
      DIR: .
      FILE: main
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: latexmk-action
        uses: yegor256/latexmk-action@0.7.1
        with:
          cmd: latexmk
          path: ${{ env.FILE }}
          opts: -pdf
          #packages: acmart tikz
      #- name: Install TeXlive
        #run: sudo apt-get update && sudo apt-get install texlive texlive-publishers texlive-science latexmk cm-super
        #run: apt-get update && apt-get -y install latexmk && apt-get clean
      #- name: LaTeX compile
        #working-directory: ${{ env.DIR }}
        #run: latexmk ${{ env.FILE }}
      - name: move
        run: mkdir -p github_artifacts && mv ${{ env.DIR }}/${{ env.FILE }}.pdf ./github_artifacts/
      - name: Upload pdf as artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.FILE }}.pdf
          path: ./github_artifacts
  deploy:
    # Edit here if compiling multiple papers
    needs: [paper]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: github_artifacts
      - name: move
        run: mkdir -p github_deploy && mv github_artifacts/*/* github_deploy
      - name: deploy on orphan branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github_deploy
          publish_branch: build
          force_orphan: true